/**
 * 출생지별 경도표 — **자동 생성 파일이다. 손으로 고치지 말 것.**
 *
 *   node scripts/build-birthplaces.mjs
 *
 * 출처: 통계청 센서스용 행정구역경계 2013 (southkorea-maps, kostat/2013)
 * https://raw.githubusercontent.com/southkorea/southkorea-maps/master/kostat/2013/json/skorea_municipalities_geo_simple.json
 *
 * 경도는 행정구역 경계의 **면적가중 중심점**이며 소수 둘째 자리까지만 쓴다
 * (0.01° = 0.04분 · 보정은 분 단위로 반올림된다). 광역시·특별시는 구를 나누지 않고,
 * 도 지역은 시/군까지 두되 통합시의 구는 모시로 합쳤다. 근거는 `docs/saju-validation.md`.
 *
 * 클라이언트에서 import 하므로 `server-only` 를 붙이지 않는다.
 */

export interface Birthplace {
  /** 시/도 표시명 (2단계 선택의 1단계) */
  sido: string;
  /** 시/군 표시명. 광역시는 시/도 이름과 같다 */
  name: string;
  /** 면적가중 중심점의 경도(도) */
  longitude: number;
}

/** 시/도 표시 순서 — 자료 코드 순(서울→제주)이다. */
export const BIRTHPLACE_SIDO = [
  "서울",
  "부산",
  "대구",
  "인천",
  "광주",
  "대전",
  "울산",
  "세종",
  "경기",
  "강원",
  "충북",
  "충남",
  "전북",
  "전남",
  "경북",
  "경남",
  "제주",
] as const;

export const BIRTHPLACES: readonly Birthplace[] = [
  { sido: "서울", name: "서울", longitude: 126.99 },
  { sido: "부산", name: "기장군", longitude: 129.2 },
  { sido: "부산", name: "부산", longitude: 129.01 },
  { sido: "대구", name: "달성군", longitude: 128.5 },
  { sido: "대구", name: "대구", longitude: 128.63 },
  { sido: "인천", name: "강화군", longitude: 126.41 },
  { sido: "인천", name: "옹진군", longitude: 125.49 },
  { sido: "인천", name: "인천", longitude: 126.63 },
  { sido: "광주", name: "광주", longitude: 126.84 },
  { sido: "대전", name: "대전", longitude: 127.4 },
  { sido: "울산", name: "울산", longitude: 129.37 },
  { sido: "울산", name: "울주군", longitude: 129.19 },
  { sido: "세종", name: "세종", longitude: 127.26 },
  { sido: "경기", name: "가평군", longitude: 127.45 },
  { sido: "경기", name: "고양시", longitude: 126.84 },
  { sido: "경기", name: "과천시", longitude: 127.01 },
  { sido: "경기", name: "광명시", longitude: 126.87 },
  { sido: "경기", name: "광주시", longitude: 127.3 },
  { sido: "경기", name: "구리시", longitude: 127.13 },
  { sido: "경기", name: "군포시", longitude: 126.93 },
  { sido: "경기", name: "김포시", longitude: 126.63 },
  { sido: "경기", name: "남양주시", longitude: 127.24 },
  { sido: "경기", name: "동두천시", longitude: 127.08 },
  { sido: "경기", name: "부천시", longitude: 126.79 },
  { sido: "경기", name: "성남시", longitude: 127.12 },
  { sido: "경기", name: "수원시", longitude: 127.01 },
  { sido: "경기", name: "시흥시", longitude: 126.79 },
  { sido: "경기", name: "안산시", longitude: 126.77 },
  { sido: "경기", name: "안성시", longitude: 127.31 },
  { sido: "경기", name: "안양시", longitude: 126.93 },
  { sido: "경기", name: "양주시", longitude: 127 },
  { sido: "경기", name: "양평군", longitude: 127.58 },
  { sido: "경기", name: "여주시", longitude: 127.62 },
  { sido: "경기", name: "연천군", longitude: 127 },
  { sido: "경기", name: "오산시", longitude: 127.05 },
  { sido: "경기", name: "용인시", longitude: 127.22 },
  { sido: "경기", name: "의왕시", longitude: 126.99 },
  { sido: "경기", name: "의정부시", longitude: 127.07 },
  { sido: "경기", name: "이천시", longitude: 127.48 },
  { sido: "경기", name: "파주시", longitude: 126.81 },
  { sido: "경기", name: "평택시", longitude: 127 },
  { sido: "경기", name: "포천시", longitude: 127.25 },
  { sido: "경기", name: "하남시", longitude: 127.21 },
  { sido: "경기", name: "화성시", longitude: 126.88 },
  { sido: "강원", name: "강릉시", longitude: 128.84 },
  { sido: "강원", name: "고성군", longitude: 128.4 },
  { sido: "강원", name: "동해시", longitude: 129.06 },
  { sido: "강원", name: "삼척시", longitude: 129.12 },
  { sido: "강원", name: "속초시", longitude: 128.52 },
  { sido: "강원", name: "양구군", longitude: 128 },
  { sido: "강원", name: "양양군", longitude: 128.6 },
  { sido: "강원", name: "영월군", longitude: 128.5 },
  { sido: "강원", name: "원주시", longitude: 127.93 },
  { sido: "강원", name: "인제군", longitude: 128.26 },
  { sido: "강원", name: "정선군", longitude: 128.74 },
  { sido: "강원", name: "철원군", longitude: 127.36 },
  { sido: "강원", name: "춘천시", longitude: 127.74 },
  { sido: "강원", name: "태백시", longitude: 128.98 },
  { sido: "강원", name: "평창군", longitude: 128.49 },
  { sido: "강원", name: "홍천군", longitude: 128.08 },
  { sido: "강원", name: "화천군", longitude: 127.69 },
  { sido: "강원", name: "횡성군", longitude: 128.08 },
  { sido: "충북", name: "괴산군", longitude: 127.83 },
  { sido: "충북", name: "단양군", longitude: 128.39 },
  { sido: "충북", name: "보은군", longitude: 127.73 },
  { sido: "충북", name: "영동군", longitude: 127.82 },
  { sido: "충북", name: "옥천군", longitude: 127.66 },
  { sido: "충북", name: "음성군", longitude: 127.62 },
  { sido: "충북", name: "제천시", longitude: 128.14 },
  { sido: "충북", name: "증평군", longitude: 127.61 },
  { sido: "충북", name: "진천군", longitude: 127.44 },
  { sido: "충북", name: "청원군", longitude: 127.5 },
  { sido: "충북", name: "청주시", longitude: 127.47 },
  { sido: "충북", name: "충주시", longitude: 127.9 },
  { sido: "충남", name: "계룡시", longitude: 127.24 },
  { sido: "충남", name: "공주시", longitude: 127.08 },
  { sido: "충남", name: "금산군", longitude: 127.48 },
  { sido: "충남", name: "논산시", longitude: 127.16 },
  { sido: "충남", name: "당진시", longitude: 126.65 },
  { sido: "충남", name: "보령시", longitude: 126.6 },
  { sido: "충남", name: "부여군", longitude: 126.86 },
  { sido: "충남", name: "서산시", longitude: 126.47 },
  { sido: "충남", name: "서천군", longitude: 126.71 },
  { sido: "충남", name: "아산시", longitude: 126.98 },
  { sido: "충남", name: "예산군", longitude: 126.79 },
  { sido: "충남", name: "천안시", longitude: 127.2 },
  { sido: "충남", name: "청양군", longitude: 126.86 },
  { sido: "충남", name: "태안군", longitude: 126.29 },
  { sido: "충남", name: "홍성군", longitude: 126.62 },
  { sido: "전북", name: "고창군", longitude: 126.62 },
  { sido: "전북", name: "군산시", longitude: 126.75 },
  { sido: "전북", name: "김제시", longitude: 126.91 },
  { sido: "전북", name: "남원시", longitude: 127.44 },
  { sido: "전북", name: "무주군", longitude: 127.72 },
  { sido: "전북", name: "부안군", longitude: 126.66 },
  { sido: "전북", name: "순창군", longitude: 127.09 },
  { sido: "전북", name: "완주군", longitude: 127.22 },
  { sido: "전북", name: "익산시", longitude: 126.99 },
  { sido: "전북", name: "임실군", longitude: 127.24 },
  { sido: "전북", name: "장수군", longitude: 127.55 },
  { sido: "전북", name: "전주시", longitude: 127.12 },
  { sido: "전북", name: "정읍시", longitude: 126.91 },
  { sido: "전북", name: "진안군", longitude: 127.43 },
  { sido: "전남", name: "강진군", longitude: 126.77 },
  { sido: "전남", name: "고흥군", longitude: 127.32 },
  { sido: "전남", name: "곡성군", longitude: 127.27 },
  { sido: "전남", name: "광양시", longitude: 127.66 },
  { sido: "전남", name: "구례군", longitude: 127.51 },
  { sido: "전남", name: "나주시", longitude: 126.72 },
  { sido: "전남", name: "담양군", longitude: 127 },
  { sido: "전남", name: "목포시", longitude: 126.41 },
  { sido: "전남", name: "무안군", longitude: 126.42 },
  { sido: "전남", name: "보성군", longitude: 127.16 },
  { sido: "전남", name: "순천시", longitude: 127.39 },
  { sido: "전남", name: "신안군", longitude: 126.05 },
  { sido: "전남", name: "여수시", longitude: 127.66 },
  { sido: "전남", name: "영광군", longitude: 126.46 },
  { sido: "전남", name: "영암군", longitude: 126.64 },
  { sido: "전남", name: "완도군", longitude: 126.78 },
  { sido: "전남", name: "장성군", longitude: 126.77 },
  { sido: "전남", name: "장흥군", longitude: 126.92 },
  { sido: "전남", name: "진도군", longitude: 126.23 },
  { sido: "전남", name: "함평군", longitude: 126.54 },
  { sido: "전남", name: "해남군", longitude: 126.52 },
  { sido: "전남", name: "화순군", longitude: 127.03 },
  { sido: "경북", name: "경산시", longitude: 128.81 },
  { sido: "경북", name: "경주시", longitude: 129.24 },
  { sido: "경북", name: "고령군", longitude: 128.31 },
  { sido: "경북", name: "구미시", longitude: 128.36 },
  { sido: "경북", name: "군위군", longitude: 128.65 },
  { sido: "경북", name: "김천시", longitude: 128.08 },
  { sido: "경북", name: "문경시", longitude: 128.15 },
  { sido: "경북", name: "봉화군", longitude: 128.92 },
  { sido: "경북", name: "상주시", longitude: 128.07 },
  { sido: "경북", name: "성주군", longitude: 128.24 },
  { sido: "경북", name: "안동시", longitude: 128.78 },
  { sido: "경북", name: "영덕군", longitude: 129.32 },
  { sido: "경북", name: "영양군", longitude: 129.15 },
  { sido: "경북", name: "영주시", longitude: 128.6 },
  { sido: "경북", name: "영천시", longitude: 128.94 },
  { sido: "경북", name: "예천군", longitude: 128.42 },
  { sido: "경북", name: "울릉군", longitude: 130.86 },
  { sido: "경북", name: "울진군", longitude: 129.32 },
  { sido: "경북", name: "의성군", longitude: 128.62 },
  { sido: "경북", name: "청도군", longitude: 128.79 },
  { sido: "경북", name: "청송군", longitude: 129.06 },
  { sido: "경북", name: "칠곡군", longitude: 128.46 },
  { sido: "경북", name: "포항시", longitude: 129.31 },
  { sido: "경남", name: "거제시", longitude: 128.63 },
  { sido: "경남", name: "거창군", longitude: 127.91 },
  { sido: "경남", name: "고성군", longitude: 128.3 },
  { sido: "경남", name: "김해시", longitude: 128.85 },
  { sido: "경남", name: "남해군", longitude: 127.94 },
  { sido: "경남", name: "밀양시", longitude: 128.79 },
  { sido: "경남", name: "사천시", longitude: 128.04 },
  { sido: "경남", name: "산청군", longitude: 127.89 },
  { sido: "경남", name: "양산시", longitude: 129.04 },
  { sido: "경남", name: "의령군", longitude: 128.28 },
  { sido: "경남", name: "진주시", longitude: 128.13 },
  { sido: "경남", name: "창녕군", longitude: 128.5 },
  { sido: "경남", name: "창원시", longitude: 128.6 },
  { sido: "경남", name: "통영시", longitude: 128.38 },
  { sido: "경남", name: "하동군", longitude: 127.78 },
  { sido: "경남", name: "함안군", longitude: 128.43 },
  { sido: "경남", name: "함양군", longitude: 127.72 },
  { sido: "경남", name: "합천군", longitude: 128.14 },
  { sido: "제주", name: "서귀포시", longitude: 126.58 },
  { sido: "제주", name: "제주시", longitude: 126.53 },
];
